### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by adamwalker**
Hi

I attempted to use your library but ran into a few issues. The fixes are in this pull request.

Adam

### CODE REVIEW

**Comment by victoredwardocallaghan** [comment]
Hi Adam,

Thank you for these patches and getting upstream to me! Sorry for the delay.

Just a bit of background, the reason why the bounds type was put there was to remind me to ensure those actions should do boundary checking. Ideally I would like to do this at the type level, this can be done with dependant types but I am not sure if a integer interval can be used as a predicate for a type in Haskell? Otherwise we need a semantic here for values that are not supported, one possible semantic is to clamp the values to the respective max/min and throw a debug message, what are your views on this?

Kind Regards,
Edward.
btw, I see you went to UNSW also :)

**Comment by adamwalker** [comment]
No worries. Thanks for merging them and thanks for the library!
I don't know of any ways to ensure that the bounds are enforced at the type level. There's this: https://wiki.haskell.org/Smart_constructors, but its still a runtime check. 
If the user supplies an invalid value, I think clamping makes sense, especially since this is what libbladerf does (I think). I think there should also be a very visible debug message in this case.

Also - I was wondering - have you been using a BladeRF with haskell? I think that libraries like pipes, and to some extent vector make it an ideal language for software defined radio.

**Comment by victoredwardocallaghan** [comment]
Hi Adam,

Yes, that is exactly what I've been doing with it. Would you like to collaborate a bit on this? I've been making a reimplementation of the first two layers of OpenBTS in Haskell. You are correct that Vector over the Complex field is the data path since QAM is essentially "universal modulation", so a EDSL around this idea using Pipes is exactly what I had in mind.

I started on this stuff here:
https://github.com/victoredwardocallaghan/HaskellDSP
and here:
https://github.com/victoredwardocallaghan/hbts

But life took over for a bit, happy to pick up where I left off if you are interested?

Cheers,
Edward.

**Comment by adamwalker** [comment]
Unfortunately, I wouldn't have anywhere near the required knowledge to hack on the lower layers of OpenBTS. 

I started this, though: https://github.com/adamwalker/sdr. It only does analog demodulation, but I will be adding digital demodulation in the future.

Cheers,
Adam

**Pull request merged**
